# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on: [push]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - uses: actions/checkout@v2
    - name: Test
      uses: ./
      env:
        FIREBASE_TOKEN: 1//03W8MhNPLrnvWCgYIARAAGAMSNwF-L9IrtMsPyYYAlKOBIrXnrI-AQvAsNm8t0pKMqDDXQLwCiWnOVnWutsaVDT6-CAV1YDQvsrM
      with:
        firebase_project: elocatus-dev
        firebase_target: dx-ui
        firebase_hosting: dl-ui-dev
        firebase_predeploy: false

